### ISSUE TITLE
pip install rejson==0.5.0 fails

### ISSUE THREAD

**Issue by manjiler** [RedisJSON/redisjson-py#28]
Collecting rejson==0.5.0
  Downloading 

> https://files.pythonhosted.org/packages/33/31/d85098ce0718e86b147296b296fd66b5f82f3d638d60a8798e6824b71a7a/rejson-0.5.0.tar.gz
>     ERROR: Command errored out with exit status 1:
>      command: /usr/local/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ehcrp3qu/rejson/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ehcrp3qu/rejson/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-ehcrp3qu/rejson/pip-egg-info
>          cwd: /tmp/pip-install-ehcrp3qu/rejson/
>     Complete output (9 lines):
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-install-ehcrp3qu/rejson/setup.py", line 24, in <module>
>         version = get_version('rejson')
>       File "/tmp/pip-install-ehcrp3qu/rejson/setup.py", line 14, in get_version
>         init_py = open(os.path.join(package, '__init__.py')).read()
>       File "/usr/local/lib/python3.6/encodings/ascii.py", line 26, in decode
>         return codecs.ascii_decode(input, self.errors)[0]
>     UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1425: ordinal not in range(128)

ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

I am seeing this on Mac OS 10.5 and Centos 7.4
Python Version - 3.6.4

**Comment by manjiler** [comment]
@gkorland Can you help with this?

**Comment by gkorland** [comment]
Thanks I'll give it a look, it seems to work fine on my Ubuntu. @itamarhaber

**Comment by manjiler** [comment]
@itamarhaber Branch fix-28 works! 
```
Processing ./redisjson-py
Building wheels for collected packages: rejson
  Running setup.py bdist_wheel for rejson ... done
  Stored in directory: /Users/test/Library/Caches/pip/wheels/b4/ea/62/93af87b08b7c449fc10a86fb22b7868add171e4d7a5e8ba8a0
Successfully built rejson
Installing collected packages: rejson
Successfully installed rejson-0.5.1
```

Thanks for fixing it.
When do would the PR get closed and newer be available via pip?

**Comment by ykvch** [comment]
Could You please add this fix to https://github.com/RedisJSON/redisjson-py/blob/master/setup.py#L18 as well: `  with io.open(f, encoding="utf-8") as I:`
Since currently it causes install error with FreeBSD 12 + Python 3.6.1

**Comment by gkorland** [comment]
@ykvch can you please submit a PR

**Comment by ykvch** [comment]
@gkorland , could You please check the PR above.
