### ISSUE TITLE
Issue for Jsonpath filter support

### ISSUE THREAD

**Issue by cw1427** [RedisJSON/redisjson-py#35]
It looks like doesn't support jsonpath filter feature?  Like for example:   "[?(@.name=='Admin')]"

Refer:  https://support.smartbear.com/alertsite/docs/monitors/api/endpoint/jsonpath.html

**Comment by gkorland** [comment]
You should check RedisJSON2.

https://github.com/RedisJSON/redisjson2

**Comment by cw1427** [comment]
WOW, that is awesome.  @gkorland  will think about migrate to redisjson2.  Is it ready the redison-py or other language client library to support redisjons2 ?

**Comment by gkorland** [comment]
Yes, the existing clients should work with it

**Comment by cw1427** [comment]
Perfect, I will have a trial.  Thanks a lot @gkorland.

**Comment by cw1427** [comment]
Hi @gkorland :

I go through the redisjson-py master branch code, but didn't find any command interface regard redisjson2.  Are you sure that it had already been supported?

**Comment by gkorland** [comment]
the client doesn't support indexes yet, but you can pass Path supports any string based path.

e.g.
```
rj.jsonget('obj', Path('$.truth.coord[?(@.name==\'Admin\')]')) 
```
