### ISSUE TITLE
Support json.toggle and json.clear commands

### ISSUE THREAD

**Issue by oshadmi** [RedisJSON/redisjson-py#50]
Add support for the following commands:
`json.toggle`
`json.clear`

**Comment by AvitalFineRedis** [comment]
@oshadmi Do we have documentation for these commands?

**Comment by oshadmi** [comment]
@AvitalFineRedis No documentation yet.
Added a comment here in the meantime
https://github.com/tombatron/NReJSON/issues/13#issuecomment-890521251
