### ISSUE TITLE
moduleNotFoundError: No module named "redis._compat"

### ISSUE THREAD

**Issue by NickLucche** [RedisJSON/redisjson-py#67]
This import error pops up when trying to import `rejson` using latest build for `redis-py` (`pip install redis` before `rejson`).  

A temporary workaround is to install previous redis-py version 3.5.3 before installing rejson, as in:
```
p -m pip uninstall -y redis
p -m pip install redis==3.5.3
p -m pip install rejson
```

**Comment by chayim** [comment]
Hi @NickLucche thank you for reporting! json support is now in redis-py 4.0.0, maybe you'd like to try it! There are some small API changes in order to bring it together, but ultimately the tests in tests/test_json.py will help.

**Comment by NickLucche** [comment]
Thanks for the response, I'll be sure to check that out!

**Comment by chayim** [comment]
Awesome! FYI I'm working on pushing upstream a (currently last) version of redijson just to pin to 3.5.3. I feel like that would be fair!
