### ISSUE TITLE
Error installing the package

### ISSUE THREAD

**Issue by ddomingof** [RedisJSON/redisjson-py#69]
I am trying to install the package on Python 3.8 and I am getting this error.

`pip install rejson`

`  ERROR: Failed building wheel for rejson
Failed to build rejson
ERROR: Could not build wheels for rejson which use PEP 517 and cannot be installed directl`

**Comment by lmiguelmh** [comment]
I had the same problem with `redisearch` library, it seems that [the library was deprecated some hours ago](https://pypi.org/project/redisearch/). 

As a temporal solution I had to force the version 2.0.0 on my requirements file.

`redisearch==2.0.0`
